import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/lib/sessionProvider/Provider";
const inter = Inter({ subsets: ["latin"] });
import { SearcProvider } from "@/context/SearchCtx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearcProvider>
          <Provider>{children}</Provider>
        </SearcProvider>
      </body>
    </html>
  );
}
